a = float(input("A : "))
b = float(input("B : "))
suma = abs(a) + abs(b)
raz = abs(a) - abs(b)
proi = abs(a) * abs(b)
chot = abs(a) / abs(b)
print(f'Сумма = {suma}\nРазност = {raz}\nПроизвидение = {proi}\nЧотност = {chot}')
